### ISSUE TITLE
What is PATH_COMPONENTS ?

### ISSUE THREAD

**Issue by Len-Li** [hujiecpp/ISTR#1]
Hi, thanks for your awesome work.

I try to retrain the network, while I found that 
`    cfg.MODEL.ISTR.PATH_COMPONENTS = "./datasets/coco/components/coco_2017_train_class_agnosticTrue_whitenTrue_sigmoidTrue_60.npz"
`
However, I can't found it in this repo. How can I get it? 

Thanks

**Comment by hujiecpp** [comment]
PATH_COMPONENTS is the parameters for PCA. It is located in: https://github.com/hujiecpp/ISTR/blob/master/projects/ISTR/LME/coco_2017_train_class_agnosticTrue_whitenTrue_sigmoidTrue_60_siz28.npz
And I also updated the config file (https://github.com/hujiecpp/ISTR/blob/master/projects/ISTR/istr/config.py) for this issue, you can check the updated file for the details.

**Comment by Len-Li** [comment]
> PATH_COMPONENTS is the parameters for PCA. It is located in: https://github.com/hujiecpp/ISTR/blob/master/projects/ISTR/LME/coco_2017_train_class_agnosticTrue_whitenTrue_sigmoidTrue_60_siz28.npz
> And I also updated the config file (https://github.com/hujiecpp/ISTR/blob/master/projects/ISTR/istr/config.py) for this issue, you can check the updated file for the details.

Thanks!
