### ISSUE TITLE
PATH_COMPONENTS: "./projects/AE/checkpoints/AE_112_256.t7"  not found

### ISSUE THREAD

**Issue by PDahal2871** [hujiecpp/ISTR#13]
I tried using config file of `projects/ISTR/configs/ISTR-AE-swinL-3x.yaml`. But the path components given in that config file is missing frorm GitHub. Is there any link of this file?

**Comment by hujiecpp** [comment]
https://drive.google.com/file/d/1b_-niQvu4aNT3Aw2FZ2WjSvwZFCP-jIr/view?usp=sharing

**Comment by hujiecpp** [comment]
> https://drive.google.com/file/d/1b_-niQvu4aNT3Aw2FZ2WjSvwZFCP-jIr/view?usp=sharing

Hi @PDahal2871 , this is the link of the missing file.

**Comment by PDahal2871** [comment]
@hujiecpp Among ISTR-PCA, ISTR-DCT, and ISTR-SMT , does ISTR-SMT have better accuracy? Can you also give its exact config file location? Thanks.
