### ISSUE TITLE
 pred_mask visualization cannot match the object

### ISSUE THREAD

**Issue by GuQingtao** [hujiecpp/ISTR#4]
I trained the model on my dataset，when run the 'demo.py' for testing, I got the result as following:
![1-01-5-pred](https://user-images.githubusercontent.com/35688106/119115251-891a7400-ba59-11eb-8022-ec8a646d02ea.jpg)
It seems like that I got the right prediction result,but the code for visualization have some problems, or else??

**Comment by luyao-cv** [comment]
You used your own datasets. Have you re-extracted features from your datasets? Extract the new .npz file, and then train your data. In addition, I want to know how much box ap and mask ap of your training final model can reach?

**Comment by GuQingtao** [comment]
> You used your own datasets. Have you re-extracted features from your datasets? Extract the new .npz file, and then train your data. In addition, I want to know how much box ap and mask ap of your training final model can reach?

I just run the train_net.py, and did not re-extracted features for my datasets to get the new .npz file , is it the reason leading to my result? 
Box:
|   AP   |  AP50  |  AP75  |  APs  |  APm  |  APl   |
|:------:|:------:|:------:|:-----:|:-----:|:-
| 96.741 | 99.787 | 98.564 |  nan  |  nan  | 96.759 |
Mask:
| 0.000 | 0.000  | 0.000  |  nan  |  nan  | 0.000 |

**Comment by luyao-cv** [comment]
I'm not sure if it is the only reason because in general, the performance is not so low, you can extract it first. In addition, you can use our trained weights to test and visualize your data.

**Comment by GuQingtao** [comment]
I have finished the problems,cause my own fault producing this error: I uesed detectron2 with pip install ,which cause a version error.Finally,use the detectron2 in this hub to fix it.

**Comment by jingxinyi** [comment]
> I'm not sure if it is the only reason because in general, the performance is not so low, you can extract it first. In addition, you can use our trained weights to test and visualize your data.

Hello, I'm sorry that I can't find your trained weights. This error（AssertionError: Checkpoint ./output/model_final.pth not found!） occurred when I test.
