### ISSUE TITLE
NMS module?

### ISSUE THREAD

**Issue by cao13jf** [hujiecpp/ISTR#7]
Hi @hujiecpp, thank you for making this project publicly available. I tried to apply this framework to an instance segmentation task of medical images. The prediction result looks good but some objects seem to be detected as multiple overlapped objects. This problem is solved by NMS in MASK RCNN. I checked the [_inference_](https://github.com/hujiecpp/ISTR/blob/967c9012ef7374c903d96cf1045c02e4ab2972ad/projects/ISTR/istr/inseg.py#L263) code but failed to find the way to overcome this problem.  Is there any counterpart (like NMS) in ISTR to filter out extra predictions? I probably missed it in the manuscirpt, sorry about that. In advance thank you.

**Comment by xiaozhen18239228065** [comment]
@cao13jf  Hello, I seem to have encountered the same problem as you. How did you solve it in the end.
